#!/usr/bin/env python3
"""Reproducibly extract the LGPL FFmpeg MPEG2 intra block decoder and VLC data.

The parser/IDCT headers are included unchanged. All block-decoder changes are
explicit replacements below: compact state, strict syntax/bounds validation,
and removal of logging / macroblock bookkeeping. No hand-maintained copy.
"""
import pathlib, re, hashlib
ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / 'et-kernels/generated'
OUT.mkdir(exist_ok=True)

def source(path):
    return (ROOT / path).read_text()

def array(path, name):
    text = source(path)
    m = re.search(r'const\s+([\w ]+)\s+' + name + r'\[[^=]+?=\s*\{(.*?)\n\};', text, re.S)
    if not m:
        raise ValueError(name)
    body = re.sub(r'/\*.*?\*/|//[^\n]*', '', m[2], flags=re.S)
    nums = [int(x, 0) for x in re.findall(r'-?0x[\da-fA-F]+|-?\d+', body)]
    return m[1], nums

def table(codes, bits=9):
    """Build FFmpeg get_vlc2 layout, root plus variable-sized subtables."""
    result = [(-1, 0)] * (1 << bits)
    long = {}
    for sym, (code, n) in enumerate(codes):
        if n <= bits:
            for j in range(code << (bits-n), (code+1) << (bits-n)):
                assert result[j] == (-1, 0)
                result[j] = (sym, n)
        else:
            long.setdefault(code >> (n-bits), []).append((sym, code, n-bits))
    for prefix, entries in sorted(long.items()):
        width = max(e[2] for e in entries)
        base = len(result)
        assert result[prefix] == (-1, 0)
        result[prefix] = (base, -width)
        result += [(-1, 0)] * (1 << width)
        for sym, code, n in entries:
            suffix = code & ((1 << n)-1)
            for j in range(suffix << (width-n), (suffix+1) << (width-n)):
                assert result[base+j] == (-1, 0)
                result[base+j] = (sym, n)
    assert len(result) < 32768
    # Exhaustively test every source code against table layout.
    for sym, (code, n) in enumerate(codes):
        word = code << (24-n)
        v, l = result[word >> (24-bits)]
        if l < 0:
            v, l2 = result[v + ((word >> (24-bits+l)) & ((1 << -l)-1))]
            assert l2 + bits == n
        else:
            assert l == n
        assert v == sym
    return result

header = '/* Generated by et-kernels/scripts/generate.py; do not edit.\n * LGPL-2.1-or-later; FFmpeg tables copyright Fabrice Bellard (2000,2001),\n * Michael Niedermayer (2002-2004). */\n'
data = header
runs = array('libavcodec/mpeg12data.c', 'ff_mpeg12_run')[1]
levels = array('libavcodec/mpeg12data.c', 'ff_mpeg12_level')[1]
for src, dst, rl in [('ff_mpeg1_vlc_table', 'ff_mpeg1_rl_vlc', True),
                     ('ff_mpeg2_vlc_table', 'ff_mpeg2_rl_vlc', True),
                     ('ff_mpeg12_mbAddrIncrTable', 'et_mbincr_vlc', False),
                     ('ff_mpeg12_mbPatTable', 'et_mbpat_vlc', False),
                     ('ff_mpeg12_mbMotionVectorTable', 'et_mv_vlc', False)]:
    nums = array('libavcodec/mpeg12data.c', src)[1]
    values = table(list(zip(nums[::2], nums[1::2])))
    if rl:
        entries = [(s, n, 0) if n < 0 else
                   (-32768, 0, 0) if n == 0 else
                   (levels[s], n, runs[s]+1) if s < len(runs) else
                   (0 if s == len(runs) else 127, n, 0)
                   for s, n in values]
    else:
        entries = values
    data += f'static const {"RL_VLC_ELEM" if rl else "VLCElem"} {dst}[] = {{\n'
    for i in range(0, len(entries), 8):
        data += '    ' + ', '.join('{' + ','.join(map(str,e)) + '}' for e in entries[i:i+8]) + ',\n'
    data += '};\n'
for kind in ['lum','chroma']:
    codes = array('libavcodec/mpeg12data.c', f'ff_mpeg12_vlc_dc_{kind}_code')[1]
    bits = array('libavcodec/mpeg12data.c', f'ff_mpeg12_vlc_dc_{kind}_bits')[1]
    values = table(list(zip(codes,bits)))
    data += f'static const VLCElem ff_dc_{kind}_vlc[] = {{\n'
    for i in range(0, len(values), 8):
        data += '    ' + ', '.join('{%d,%d}' % e for e in values[i:i+8]) + ',\n'
    data += '};\n'
for path, name in [('libavcodec/mpegvideodata.c','ff_alternate_vertical_scan'),
                   ('libavcodec/mathtables.c','ff_zigzag_direct'),
                   ('libavcodec/mpegvideodata.c','ff_mpeg2_non_linear_qscale')]:
    typ, nums = array(path,name)
    data += f'static const {typ} et_{name}[] = {{' + ','.join(map(str,nums)) + '};\n'
# Macroblock flag values are the MPEG syntax flags in upstream comments,
# not FFmpeg's larger internal MB_TYPE_* bitset.
for kind in ['p', 'b']:
    name = 'table_mb_' + kind + 'type'
    nums = array('libavcodec/mpeg12.c', name)[1]
    decl = re.search(name + r'\[[^=]+?=\s*\{(.*?)\n\};', source('libavcodec/mpeg12.c'), re.S)[1]
    flags = [int(v, 16) for v in re.findall(r'// 0x([0-9A-Fa-f]+)', decl)]
    values = table(list(zip(nums[::2], nums[1::2])))
    assert len(flags) == len(nums)//2
    data += f'static const VLCElem et_mb{kind}type_vlc[] = {{\n'
    for i in range(0, len(values), 8):
        data += '    ' + ', '.join('{%d,%d}' % (flags[v] if n > 0 else v,n) for v,n in values[i:i+8]) + ',\n'
    data += '};\n'
(OUT / 'tables.h').write_text(data)

text = source('libavcodec/mpeg12dec.c')
start = text.index('static inline int mpeg2_decode_block_intra(')
end = text.index('\n/******************************************/',start)
block = text[start:end]
# Exact, audited substitutions. Fail regeneration if upstream changes these.
def replace(old, new):
    global block
    assert block.count(old) == 1, old
    block = block.replace(old,new)
replace('MpegEncContext *s', 'ETBlockState *s')
replace('diff = decode_dc(&s->gb, component);', 'diff = et_decode_dc(&s->gb, component);\n    if (diff == INT_MIN) return ET_DECODE_BAD_SLICE;')
replace('s->last_dc[component] = dc;', 'if (dc < 0 || dc >= (1 << (8 + s->intra_dc_precision)))\n        return ET_DECODE_BAD_SLICE;\n    s->last_dc[component] = dc;')
replace('    ff_tlog(s->avctx, "dc=%d\\n", block[0]);\n', '')
replace('            if (level == 127) {', '            if (level == -32768 || re_index > (unsigned)s->valid_bits)\n                return ET_DECODE_BAD_SLICE;\n            if (level == 127) {')
replace('                LAST_SKIP_BITS(re, &s->gb, 12);', '                LAST_SKIP_BITS(re, &s->gb, 12);\n                if (level == 0 || level == -2048) return ET_DECODE_BAD_SLICE;')
replace('    check_scantable_index(s, i);', '    if (i > MAX_INDEX || get_bits_count(&s->gb) > s->valid_bits)\n        return ET_DECODE_BAD_SLICE;')
replace('    s->block_last_index[n] = i;\n', '')
license = text[:text.index('/**')]
(OUT / 'block_intra.h').write_text((license + header + block).rstrip() + '\n')

start = text.index('static inline int mpeg2_decode_block_non_intra(')
end = text.index('static inline int mpeg2_decode_block_intra(', start)
block = text[start:end]
replace('MpegEncContext *s', 'ETBlockState *s')
replace('            if (level != 0) {', '            if (level == -32768 || level == 127 || re_index > (unsigned)s->valid_bits)\n                return ET_DECODE_BAD_SLICE;\n            if (level != 0) {')
replace('                SKIP_BITS(re, &s->gb, 12);', '                SKIP_BITS(re, &s->gb, 12);\n                if (level == 0 || level == -2048) return ET_DECODE_BAD_SLICE;')
replace('end:\n        LAST_SKIP_BITS(re, &s->gb, 2);', 'end:\n        if (i < 0 || SHOW_UBITS(re, &s->gb, 2) != 2) return ET_DECODE_BAD_SLICE;\n        LAST_SKIP_BITS(re, &s->gb, 2);')
replace('    check_scantable_index(s, i);', '    if (i > MAX_INDEX || get_bits_count(&s->gb) > s->valid_bits)\n        return ET_DECODE_BAD_SLICE;')
replace('    s->block_last_index[n] = i;\n', '')
(OUT / 'block_inter.h').write_text((license + header + block).rstrip() + '\n')

manifest = '\n'.join(f'{hashlib.sha256((ROOT/p).read_bytes()).hexdigest()}  {p}' for p in
    ['libavcodec/mpeg12.c','libavcodec/mpeg12dec.c','libavcodec/mpeg12data.c','libavcodec/mpegvideodata.c',
     'libavcodec/mathtables.c','libavcodec/get_bits.h','libavcodec/simple_idct_template.c'])+'\n'
(OUT / 'sources.sha256').write_text(manifest)
