/* SPDX-License-Identifier: LGPL-2.1-or-later */
#define _POSIX_C_SOURCE 200809L
#include "runtime.h"
#include "../capture_io.h"
#include <errno.h>
#include <inttypes.h>
#include <time.h>
static double now(void){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return t.tv_sec+t.tv_nsec*1e-9;}
static void *zero(size_t n){void *p=NULL;if(posix_memalign(&p,64,n))return NULL;memset(p,0,n);return p;}
static int number(const char *s,unsigned *v){char *e;errno=0;unsigned long n=strtoul(s,&e,10);if(errno||!*s||*e||n>1000000)return -1;*v=(unsigned)n;return 0;}
static void meter(const float *x,unsigned n,uint64_t *peak,uint64_t *clipped){for(unsigned i=0;i<n;i++){uint32_t b;memcpy(&b,x+i,4);b&=UINT32_C(0x7fffffff);if(b>*peak)*peak=b;if(b>UINT32_C(0x3f800000))++*clipped;}}
#define RT(call) do{if((rc=(call))<0){fprintf(stderr,"%s: %s (%d)\n",#call,ff_et_runtime_error(rt),rc);goto done;}}while(0)
static int producer_status(const ETAACProfileStatus *s,unsigned op,unsigned samples,uint64_t generation,uint64_t stream){return s->generation==generation&&s->stream_id==stream&&!s->result&&ETAAC_STATUS_OPERATION(s->operation_samples)==op&&ETAAC_STATUS_SAMPLES(s->operation_samples)==samples;}
static void print_profile(unsigned start,unsigned channel,const ETAACProfileStatus *s,unsigned enabled){printf("{\"type\":\"channel_ticks\",\"start\":%u,\"channel\":%u,\"profile_enabled\":%u,\"raw_hpmcounter3\":%s,\"input\":%"PRIu64",\"imdct_fft\":%"PRIu64",\"window_overlap\":%"PRIu64",\"output_finite\":%"PRIu64",\"pcm_publish\":%"PRIu64"}\n",start,channel,enabled,enabled?"true":"false",s->ticks[0],s->ticks[1],s->ticks[2],s->ticks[3],s->ticks[4]);}
int main(int argc,char **argv){
 unsigned count,harts,total,chunk,mode,op,profile;
 if(argc!=10||number(argv[3],&count)||number(argv[4],&harts)||number(argv[5],&total)||number(argv[6],&chunk)||number(argv[7],&mode)||number(argv[8],&op)||number(argv[9],&profile)||!count||count>64||(harts!=1&&harts!=32&&harts!=64)||!total||total>512||!chunk||chunk>total||total%chunk||mode>2||op>1||profile>1||(mode==2&&(op||chunk!=total))){fprintf(stderr,"usage: profile-run ELF CAPTURE CHANNELS HARTS FRAMES CHUNK MODE(0=streamed,1=resident,2=resident-meter) OP(0=synth,1=copy; mode2 synth) PROFILE\n");return 2;}
 if(!getenv("ETAAC_PROFILE_HW_GUARD")||strcmp(getenv("ETAAC_PROFILE_HW_GUARD"),"1")||!getenv("FF_ET_SYSEMU")||strcmp(getenv("FF_ET_SYSEMU"),"0")){fprintf(stderr,"Run only through profile/run-silicon.sh\n");return 2;}
 ETRuntime *rt=NULL;ETAACCapture c={0};int rc=0,ok=0;char error[512];ETAACInput *input=NULL;ETAACState *state=NULL;ETAACProfileStatus *status=NULL;float *output=NULL;
 if(capture_load(&c,argv[2])||capture_select(&c,total)){fprintf(stderr,"invalid/short capture\n");goto done;}
 size_t in_bytes=(size_t)count*total*sizeof(*input),out_bytes=(size_t)count*total*1024*sizeof(float);input=zero(in_bytes);output=zero(out_bytes);state=zero(count*sizeof(*state));status=zero(count*sizeof(*status));if(!input||!output||!state||!status)goto done;
 double t=now();for(unsigned f=0;f<total;f++)for(unsigned i=0;i<count;i++){const ETAACRecord *r=capture_record(&c,i,f);ETAACInput *in=input+(size_t)f*count+i;in->stream_id=i+1;in->sequence=r->sequence;in->shape=r->shape;in->expected_generation=f;memcpy(in->coeff,r->coeff,sizeof(in->coeff));if(!f){state[i].initialized=1;state[i].stream_id=i+1;state[i].sequence=r->previous_sequence;state[i].shape=r->previous_shape;memcpy(state[i].saved,r->before,sizeof(state[i].saved));}}double pack=now()-t;
 ETAACProfileParams p={0};p.abi_version=ETAAC_PROFILE_ABI;p.count=count;p.active_harts=harts;p.operation=op;p.profile_enable=profile;p.capacity_frames=mode?total:chunk;p.frames=chunk;p.generation=1;p.input_bytes=(uint64_t)count*p.capacity_frames*sizeof(*input);p.output_bytes=(uint64_t)count*p.capacity_frames*1024*sizeof(float);p.state_bytes=count*sizeof(*state);p.status_bytes=count*sizeof(*status);p.scratch_bytes=harts*ETAAC_SCRATCH_FLOATS*sizeof(float);
 t=now();rc=ff_et_runtime_open(&rt,argv[1],error,sizeof(error));if(rc<0){fprintf(stderr,"open: %s\n",error);goto done;}RT(ff_et_runtime_alloc(rt,p.input_bytes,&p.input_addr));RT(ff_et_runtime_alloc(rt,p.output_bytes,&p.output_addr));RT(ff_et_runtime_alloc(rt,p.state_bytes,&p.state_addr));RT(ff_et_runtime_alloc(rt,p.status_bytes,&p.status_addr));RT(ff_et_runtime_alloc(rt,p.scratch_bytes,&p.scratch_addr));RT(ff_et_runtime_write(rt,p.state_addr,state,p.state_bytes));double setup=now()-t;
 printf("{\"type\":\"config\",\"backend\":\"silicon-shire0\",\"protocol\":3,\"channels\":%u,\"harts\":%u,\"frames\":%u,\"chunk\":%u,\"mode\":%u,\"operation\":%u,\"profile_enabled\":%u,\"counter_note\":\"raw hpmcounter3 deltas; firmware PMU setup is lane-specific, so only configured harts are interpretable; zero/unprogrammed values are nonrepresentative, not universal cycles\",\"capture_contexts\":%u,\"device_bytes\":%"PRIu64",\"pack_s\":%.9f,\"setup_s\":%.9f}\n",count,harts,total,chunk,mode,op,profile,c.selected_count,p.input_bytes+p.output_bytes+p.state_bytes+p.status_bytes+p.scratch_bytes,pack,setup);
 double upload=0,launch=0,completion=0,download=0,feature=0,pcm_validation_read=0;if(mode){t=now();RT(ff_et_runtime_write(rt,p.input_addr,input,in_bytes));upload+=now()-t;}
 if(mode<2) for(unsigned start=0;start<total;start+=chunk){p.frame_offset=mode?start:0;p.generation=start+1;double u0=now();if(!mode)RT(ff_et_runtime_write(rt,p.input_addr,input+(size_t)start*count,p.input_bytes));double u1=now();RT(etaac_profile_launch(rt,&p,1));double u2=now();RT(ff_et_runtime_read(rt,status,p.status_addr,p.status_bytes));double u3=now();if(!mode)RT(ff_et_runtime_read(rt,output+(size_t)start*count*1024,p.output_addr,p.output_bytes));double u4=now();upload+=u1-u0;launch+=u2-u1;completion+=u3-u2;download+=u4-u3;for(unsigned i=0;i<count;i++){if(!producer_status(&status[i],op,chunk*1024,start+chunk,i+1)){fprintf(stderr,"bad completion slot%u\n",i);goto done;}print_profile(start,i,&status[i],profile);}printf("{\"type\":\"launch\",\"start\":%u,\"frames\":%u,\"upload_s\":%.9f,\"launch_s\":%.9f,\"completion_s\":%.9f,\"download_s\":%.9f}\n",start,chunk,u1-u0,u2-u1,u3-u2,u4-u3);}
 if(mode==2){p.frame_offset=0;p.generation=1;p.frames=total;p.operation=ETAAC_SYNTH;t=now();RT(etaac_profile_launch(rt,&p,1));launch+=now()-t;t=now();RT(ff_et_runtime_read(rt,status,p.status_addr,p.status_bytes));completion+=now()-t;for(unsigned i=0;i<count;i++){if(!producer_status(&status[i],ETAAC_SYNTH,total*1024,total,i+1)){fprintf(stderr,"bad resident producer slot%u\n",i);goto done;}print_profile(0,i,&status[i],profile);}p.operation=ETAAC_CONSUME;t=now();RT(etaac_profile_launch(rt,&p,1));feature+=now()-t;t=now();RT(ff_et_runtime_read(rt,status,p.status_addr,p.status_bytes));feature+=now()-t;for(unsigned i=0;i<count;i++){if(!producer_status(&status[i],ETAAC_CONSUME,total*1024,total,i+1)){fprintf(stderr,"bad resident consumer slot%u\n",i);goto done;}printf("{\"type\":\"channel_meter\",\"channel\":%u,\"peak_magnitude_bits\":%"PRIu64",\"count_abs_gt_1\":%"PRIu64"}\n",i,status[i].ticks[0],status[i].ticks[1]);}}
 if(mode){t=now();RT(ff_et_runtime_read(rt,output,p.output_addr,out_bytes));pcm_validation_read=now()-t;download+=pcm_validation_read;}t=now();RT(ff_et_runtime_read(rt,state,p.state_addr,p.state_bytes));double state_read=now()-t;t=now();for(unsigned i=0;i<count;i++){uint64_t peak=0,clipped=0;for(unsigned f=0;f<total;f++){const ETAACRecord *r=capture_record(&c,i,f);float *actual=output+((size_t)f*count+i)*1024;const float *expected=op?r->coeff:r->output;if(memcmp(actual,expected,1024*sizeof(float))){fprintf(stderr,"PCM mismatch frame%u slot%u\n",f,i);goto done;}meter(r->output,1024,&peak,&clipped);if(f+1==total){const float *saved=op?capture_record(&c,i,0)->before:r->after;if(memcmp(state[i].saved,saved,512*sizeof(float))||state[i].generation!=total||state[i].stream_id!=i+1||state[i].sequence!=r->sequence||state[i].shape!=r->shape||state[i].initialized!=1){fprintf(stderr,"state mismatch slot%u\n",i);goto done;}}}if(mode==2&&(status[i].ticks[0]!=peak||status[i].ticks[1]!=clipped)){fprintf(stderr,"meter mismatch slot%u\n",i);goto done;}}double compare=now()-t;
 printf("{\"type\":\"result\",\"pass\":true,\"exact_channel_frames\":%u,\"profile_enabled\":%u,\"consumer\":%s,\"pack_s\":%.9f,\"setup_s\":%.9f,\"upload_s\":%.9f,\"launch_s\":%.9f,\"completion_s\":%.9f,\"feature_status_s\":%.9f,\"pcm_validation_read_s\":%.9f,\"download_s\":%.9f,\"state_validation_s\":%.9f,\"compare_s\":%.9f,\"timed_resident_service_s\":%.9f}\n",count*total,profile,mode==2?"true":"false",pack,setup,upload,launch,completion,feature,pcm_validation_read,download,state_read,compare,launch+completion+feature);ok=1;
 done:ff_et_runtime_close(&rt);capture_free(&c);free(input);free(output);free(state);free(status);return ok?0:1;
}
