#!/usr/bin/env bash
# Explicit opt-in native test library; never a production fallback.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=${1:?Usage: build-native-runtime.sh OUTPUT_DIR [NATIVE_KERNEL_LIB]}
mkdir -p "$OUT"; OUT=$(cd "$OUT" && pwd)
echo '*** BUILDING NATIVE TEST RUNTIME — NO ET HARDWARE / NO SIMULATOR ***' >&2
KERNEL=${2:-}
if [[ -z "$KERNEL" ]]; then
    # Keep every test build artifact inside OUTPUT_DIR; generated kernel headers
    # are source-controlled by et-kernels, not regenerated by this test helper.
    mkdir -p "$OUT/kernel"
    # Explicit native instruction model for exact IDCT, SWAR reference motion.
    # Handwritten ET motion asm is independently modeled and hardware-gated.
    FLAGS=(-DET_IDCT_SIMD=1 -DET_IDCT_SIMD_MODEL=1 -DET_IDCT_ROWS=1 -DET_IDCT_PACKED=1
           -DET_CACHED_BITS=1 -DET_DIRECT_BITS=1 -DET_FAST_HEADERS=1 -DET_FAST_DC=1
           -DET_SPREAD_HARTS=1 -DET_MC_IMPL=1)
    for unit in decoder idct idct_simd; do
        ${CC:-cc} -std=c11 -O2 -g -fPIC "${FLAGS[@]}" -I"$ROOT/et-kernels/include" \
            -I"$ROOT/et-kernels/generated" -I"$ROOT" \
            -c "$ROOT/et-kernels/src/$unit.c" -o "$OUT/kernel/$unit.o"
    done
    ${AR:-ar} rcs "$OUT/kernel/libet_mpeg2_native.a" "$OUT/kernel/decoder.o" "$OUT/kernel/idct.o" "$OUT/kernel/idct_simd.o"
    # The same compiled kernel is exposed for ctypes direct-oracle tests.
    ${CC:-cc} -shared "$OUT/kernel/decoder.o" "$OUT/kernel/idct.o" "$OUT/kernel/idct_simd.o" -o "$OUT/kernel/libet_mpeg2_native.so"
    KERNEL="$OUT/kernel/libet_mpeg2_native.a"
fi
KERNEL=$(realpath "$KERNEL")
[[ -f "$KERNEL" ]] || { echo "Missing native kernel archive: $KERNEL" >&2; exit 1; }
mkdir -p "$OUT/lib/pkgconfig" "$OUT/include"
cp "$ROOT/libavcodec/et_runtime.h" "$ROOT/libavcodec/et_mpeg2_protocol.h" "$OUT/include/"
${CC:-cc} -std=c11 -O2 -g -Wall -Wextra -Werror -fPIC -I"$OUT/include" -c "$ROOT/et-tests/native-runtime.c" -o "$OUT/native-runtime.o"
${AR:-ar} rcs "$OUT/lib/libetsoc_native_test.a" "$OUT/native-runtime.o"
# Distinct library names prevent accidentally selecting a production runtime.
# Use -l (not bare archive paths): FFmpeg configure must put these AFTER objects.
case "$KERNEL" in
    *.a) cp "$KERNEL" "$OUT/lib/libetsoc_native_kernel.a"; KERNEL_LINK=-l:libetsoc_native_kernel.a ;;
    *.so) cp "$KERNEL" "$OUT/lib/libetsoc_native_kernel.so"; KERNEL_LINK=-l:libetsoc_native_kernel.so ;;
    *) echo "Expected native .a or .so kernel library: $KERNEL" >&2; exit 1 ;;
esac
cat > "$OUT/lib/pkgconfig/etsoc.pc" <<PC
prefix=$OUT
libdir=\${prefix}/lib
includedir=\${prefix}/include
Name: etsoc NATIVE TEST ONLY
Description: HOST-NATIVE TEST MPEG2 runtime; not ET hardware, not simulator
Version: 1.0
Libs: -L\${libdir} -letsoc_native_test $KERNEL_LINK -Wl,-rpath,\${libdir} -Wl,-rpath,$(dirname "$KERNEL") -lm
Cflags: -I\${includedir}
PC
printf 'NATIVE TEST ONLY: configure with PKG_CONFIG_PATH=%q --enable-etsoc\n' "$OUT/lib/pkgconfig" >&2
