/* Standalone scalar FFmpeg subset: never consume the host config.h. */
#ifndef ET_KERNEL_CONFIG_H
#define ET_KERNEL_CONFIG_H
#define HAVE_FAST_UNALIGNED 0
#define HAVE_FAST_64BIT 1
#define HAVE_BIGENDIAN 0
#define CONFIG_SAFE_BITSTREAM_READER 1
#define CONFIG_SMALL 0
#define ARCH_AARCH64 0
#define ARCH_ARM 0
#define ARCH_MIPS 0
#define ARCH_PPC 0
#define ARCH_X86 0
#define ARCH_X86_32 0
#define ARCH_X86_64 0
#define ARCH_RISCV 0
#define HAVE_INLINE_ASM 0
#define HAVE_INTRINSICS_NEON 0
#define HAVE_ASM_MOD_Q 0
#define HAVE_ATOMICS_NATIVE 0
#define HAVE_PRAGMA_DEPRECATED 1
#define HAVE_ATTRIBUTE_PACKED 1
#define HAVE_AV_CONFIG_H 1
#define HAVE_ISNAN 1
#define HAVE_ISINF 1
#define HAVE_LIBC_MSVCRT 0
#define HAVE_MMX 0
#define HAVE_MMX_INLINE 0
#define HAVE_X86ASM 0
#define HAVE_SIMD_ALIGN_16 0
#define HAVE_SIMD_ALIGN_32 0
#define HAVE_SIMD_ALIGN_64 0
#define ASSERT_LEVEL 0
#define CONFIG_SHARED 0
#define HAVE_VALGRIND_VALGRIND_H 0
#define HAVE_MALLOC_H 0
#define HAVE_MALLOC_TRIM 0
#define HAVE_MALLOC_USABLE_SIZE 0
#define HAVE_THREADS 0
#define HAVE_PTHREADS 0
#define HAVE_W32THREADS 0
#define HAVE_OS2THREADS 0
#define HAVE_FAST_CLZ 1
#define HAVE_ATANF 1
#define HAVE_ATAN2F 1
#define HAVE_POWF 1
#define HAVE_CBRT 1
#define HAVE_CBRTF 1
#define HAVE_COPYSIGN 1
#define HAVE_COSF 1
#define HAVE_ERF 1
#define HAVE_EXPF 1
#define HAVE_EXP2 1
#define HAVE_EXP2F 1
#define HAVE_ISFINITE 1
#define HAVE_HYPOT 1
#define HAVE_LDEXPF 1
#define HAVE_LLRINT 1
#define HAVE_LLRINTF 1
#define HAVE_LOG2 1
#define HAVE_LOG2F 1
#define HAVE_LOG10F 1
#define HAVE_SINF 1
#define HAVE_RINT 1
#define HAVE_LRINT 1
#define HAVE_LRINTF 1
#define HAVE_ROUND 1
#define HAVE_ROUNDF 1
#define HAVE_TRUNC 1
#define HAVE_TRUNCF 1
#endif
